name: fix code styling

on: [push]

jobs:
  pint:
    uses: laravel/.github/.github/workflows/coding-standards.yml@main
    with:
      message: "Pint: fix code styling"

  # eslint:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       stack: [react, vue]
  #       laravel: [11]
  #       args: ["--ssr --dark --eslint", "--ssr --dark --eslint --typescript"]

  #   name: Lint Stubs - Laravel ${{ matrix.laravel }} - ${{ matrix.stack }} ${{ matrix.args }}

  #   steps:
  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: 8.2
  #         extensions: dom, curl, libxml, mbstring, zip
  #         ini-values: error_reporting=E_ALL
  #         tools: composer:v2
  #         coverage: none

  #     - name: Setup Laravel
  #       run: |
  #         composer create-project laravel/laravel:^${{ matrix.laravel }} .
  #         composer require laravel/breeze:@dev --no-interaction --no-update
  #         composer config repositories.breeze '{"type": "path", "url": "breeze"}' --file composer.json

  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         path: 'breeze'

  #     - name: Install Breeze
  #       run: |
  #         composer update "laravel/breeze" --prefer-dist --no-interaction --no-progress -W
  #         php artisan breeze:install ${{ matrix.stack }} ${{ matrix.args }}

  #     - name: Install NPM dependencies
  #       run: npm i
      
  #     - name: Run ESLint
  #       run: npm run lint

  #     - name: Apply ESLint fixes
  #       run: |
  #         if [[ "${{ matrix.args }}" == *"--typescript"* ]]; then
  #           rsync -av --exclude='bootstrap.ts' resources/js/ breeze/stubs/inertia-${{ matrix.stack }}-ts/resources/js/
  #         else
  #           rsync -av --exclude='bootstrap.js' resources/js/ breeze/stubs/inertia-${{ matrix.stack }}/resources/js/
  #         fi

  #     - name: Upload ESLint fixes
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: eslint-fixes-${{ matrix.stack }}-${{ matrix.args }}
  #         path: breeze
  #         retention-days: 1

  # commit-changes:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - pint
  #     - eslint
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Download all ESLint fixes
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: breeze

  #     - name: Merge ESLint fixes
  #       run: |
  #         for dir in breeze/*; do
  #           cp -r "$dir"/* .
  #         done

  #         rm -rf breeze
      
  #     # We need to pull the latest changes because the `pint` job might have fixed some code style issues.
  #     - name: Pull Remote Changes
  #       run: git pull

  #     - name: Commit changes
  #       uses: stefanzweifel/git-auto-commit-action@v5
  #       with:
  #         commit_message: "ESLint: fix code styling"
