name: fix code styling

on: [push]

jobs:
  pint:
    uses: laravel/.github/.github/workflows/coding-standards.yml@main
    with:
      message: "Pint: fix code styling"

  eslint:
    name: Lint stubs for Inertia stacks
    runs-on: ubuntu-latest
    needs: pint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # We need to pull the latest changes because the `pint` job might have pushed changes
      - name: Pull Remote Changes
        run: git pull

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM packages
        run: npm install

      - name: Run ESLint
        run: |
          for stack in react react-ts vue vue-ts; do
            npm run lint:$stack
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ESLint: fix code styling"
