name: tests

on:
  push:
    branches:
      - master
      - eslint
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stub-tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        stack: [blade, livewire, livewire-functional, react, vue, api]
        laravel: [11]
        args: ["", --pest]
        include:
          - stack: vue
            args: --ssr --eslint
            laravel: 11
          - stack: vue
            args: --ssr --eslint --typescript
            laravel: 11
          - stack: react
            args: --ssr --eslint
            laravel: 11
          - stack: react
            args: --ssr --eslint --typescript
            laravel: 11

    name: Test Stubs - Laravel ${{ matrix.laravel }} - ${{ matrix.stack }} ${{ matrix.args }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Setup Laravel
        run: |
          composer create-project laravel/laravel:^${{ matrix.laravel }} .
          composer require laravel/breeze:@dev --no-interaction --no-update
          composer config repositories.breeze '{"type": "path", "url": "breeze"}' --file composer.json

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'breeze'

      - name: Install Breeze
        run: |
          composer update "laravel/breeze" --prefer-dist --no-interaction --no-progress -W
          php artisan breeze:install ${{ matrix.stack }} ${{ matrix.args }}

      - name: Install NPM dependencies
        if: matrix.stack != 'api'
        run: npm i

      - name: Compile assets
        if: matrix.stack != 'api'
        run: npm run build
      
      - name: Run ESLint
        if: matrix.stack == 'vue' || matrix.stack == 'react'
        run: npm run lint

      - name: Apply ESLint fixes
        if: matrix.stack == 'vue' || matrix.stack == 'react'
        run: |
          if [[ "${{ matrix.args }}" == *"--typescript"* ]]; then
            cp -r resources/js breeze/stubs/inertia-${{ matrix.stack }}-ts/resources/js
          else
            cp -r resources/js breeze/stubs/inertia-${{ matrix.stack }}/resources/js
          fi

      - name: Commit changes
        if: matrix.stack == 'vue' || matrix.stack == 'react'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: breeze
          commit_message: format code

      - name: Execute tests
        run: ${{ matrix.args == '--pest' && 'vendor/bin/pest' || 'vendor/bin/phpunit' }}
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
